version: "3"
services:
  api:
    build:
      context: ./api
    ports:
      - 8080:8080
  app:
    build:
      context: ./app
    depends_on:
      - api
    ports:
      - 8081:8081
  proxy:
    build: ./proxy
    depends_on:
      - api
      - app
    ports:
      - 80:8082
